---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino-example

resources:
- ../../base

images:
- name: postgres
  newName: gcr.io/myproject/postgres
  newTag: v16.4-customtag
