---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- hive-ingress.yaml
- tcp-services-configmap.yaml

configMapGenerator:
- name: hive-nginx-params
  envs:
  - params.env

replacements:
- source:
    fieldPath: data.HIVE_DOMAINNAME
    kind: ConfigMap
    name: hive-nginx-params
    version: v1
  targets:
  - select:
      name: hive-metastore-ingress
      kind: Ingress
    fieldPaths: 
    - spec.rules.0.host
- source:
    fieldPath: data.ingress_namespace
    kind: ConfigMap
    name: hive-nginx-params
    version: v1
  targets:
  - select:
      name: tcp-services
      kind: ConfigMap
    fieldPaths:
    - metadata.namespace
  
generatorOptions:
  disableNameSuffixHash: true