---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hive-ingress.yaml
- tcp-services-configmap.yaml

configMapGenerator:
- name: hive-nginx-params
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    fieldPath: data.HIVE_DOMAINNAME
    kind: ConfigMap
    name: hive-nginx-params
    version: v1
  targets:
  - select:
      name: hive-metastore-ingress
      kind: Ingress
    fieldPaths:
    - spec.rules.0.host
- source:
    fieldPath: data.ingress_namespace
    kind: ConfigMap
    name: hive-nginx-params
    version: v1
  targets:
  - select:
      name: tcp-services
      kind: ConfigMap
      fieldPaths:
      - metadata.namespace

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: hive-metastore-ingress
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: trino-on-k8s
    app.kubernetes.io/version: v25.09.25
    kustomize.component: hive-metastore-ingress
