apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- ../../base

replicas:
- name: trino-worker
  count: 4

images:
- name: "trinodb/trino"
  newName: "gcr.io/myproject/trino"
  newTag: "474"

secretGenerator:
- name: trino-truststore
  files:
  - truststore.jks
generatorOptions:
  disableNameSuffixHash: true
  
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: trino-coordinator
      namespace: $(namespace)
    spec:
      template:
        metadata:
          labels:
            app: trino-coordinator
        spec:
          containers:
          - name: trino
            volumeMounts:
            - name: trino-cfg-vol
              mountPath: /etc/trino/catalog/hive.properties
              subPath: hive.properties
            - name: trino-cfg-vol
              mountPath: /etc/trino/catalog/postgres.properties
              subPath: postgres.properties
            - name: trino-truststore-vol
              mountPath: /usr/lib/jvm/temurin/jdk-24+36/lib/security/cacerts
              subPath: truststore.jks
            resources:
              requests:
                memory: "8G"
                cpu: "2"
              limits:
                memory: "16G"
                cpu: "4"
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: trino-worker
      namespace: $(namespace)
    spec:
      serviceName: trino-worker
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
          containers:
          - name: trino
            volumeMounts:
            - name: trino-cfg-vol
              mountPath: /etc/trino/catalog/hive.properties
              subPath: hive.properties
            - name: trino-cfg-vol
              mountPath: /etc/trino/catalog/postgres.properties
              subPath: postgres.properties
            - name: trino-truststore-vol
              mountPath: /usr/lib/jvm/temurin/jdk-24+36/lib/security/cacerts
              subPath: truststore.jks
            resources:
              requests:
                memory: "8G"
                cpu: "2"
              limits:
                memory: "16G"
                cpu: "4"
          volumes:
          - name: trino-truststore-vol
            secret:
              secretName: trino-truststore
# using ingress-gateway instead
#- patch: |-
#    apiVersion: v1
#    kind: Service
#    metadata:
#      name: trino-coordinator-service
#      namespace: $(namespace)
#    spec:
#      type: LoadBalancer
#      loadBalancerIP: "172.18.0.210"
