apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- trino-configmap.yaml
- deployment.yaml
- statefulset.yaml
- service.yaml

configMapGenerator:
- name: trino-parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: trino-secrets
  env: secrets.env

commonLabels:
  kustomize.component: trino

