apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- statefulset.yaml
- namespace.yaml
- service.yaml

configMapGenerator:
- name: trino-cm
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: trino-cm
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml

secretGenerator:
- name: trino-secrets
  env: secrets.env

commonLabels:
  kustomize.component: trino

