apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- trino-configmap.yaml
- deployment.yaml
- statefulset.yaml
- service.yaml

configMapGenerator:
- name: trino-parameters
  envs: 
  - params.env
- name: trino-access
  files:
  - trino-groups.txt
  - trino-rules.json

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: trino-secrets
  envs: 
  - secrets.env
- name: trino-passwd
  files:
  - password.db

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: trinodb
    app.kubernetes.io/name: trino
    app.kubernetes.io/part-of: trino-on-k8s
    app.kubernetes.io/version: v25.03.06
    kustomize.component: trino

