---
apiVersion: v1
kind: Service
metadata:
  name: trino-coordinator-service
  namespace: $(namespace)
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: jmx-exporter
    port: 5556
    targetPort: jmx-exporter
    protocol: TCP
  selector:
    app: trino-coordinator
