---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker
  namespace: $(namespace)
spec:
  serviceName: trino-worker 
  replicas: 3
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: trino
        image: trinodb/trino:466
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: us-west-3
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: trino-secrets
              key: S3_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: trino-secrets
              key: S3_SECRET_KEY
        volumeMounts:
        - name: trino-cfg-vol
          mountPath: /etc/trino/jvm.config
          subPath: jvm.config
        - name: trino-cfg-vol
          mountPath: /etc/trino/config.properties
          subPath: config.properties.worker
        - name: trino-cfg-vol
          mountPath: /etc/trino/node.properties
          subPath: node.properties
        - name: trino-cfg-vol
          mountPath: /etc/trino/catalog/hive.properties
          subPath: hive.properties
        - name: trino-cfg-vol
          mountPath: /etc/trino/catalog/iceberg.properties
          subPath: iceberg.properties
        - name: trino-cfg-vol
          mountPath: /etc/trino/catalog/mysql.properties
          subPath: mysql.properties
        - name: trino-tmp-data
          mountPath: /tmp
        resources:
          requests:
            memory: "2G"
            cpu: "1"
          limits:
            memory: "4G"
            cpu: "2"
        imagePullPolicy: IfNotPresent
      volumes:
        - name: trino-cfg-vol
          configMap:
            name: trino-configs
  volumeClaimTemplates:
  - metadata:
      name: trino-tmp-data
    spec:
      #storageClassName: default
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi