---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- hive-virtualservice.yaml
- hive-gateway.yaml

configMapGenerator:
- name: hive-istio-params
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true