---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mysqld-config
  namespace: $(namespace)
data:
  mysqld.cnf: |-
    [mysqld]
    key_buffer_size         = 32M
    max_allowed_packet      = 32M
    thread_stack            = 256K
    thread_cache_size       = 64
    query_cache_limit       = 8M
    query_cache_size        = 64M
    query_cache_type        = 1
    max_connections         = 550
    read_buffer_size        = 2M
    read_rnd_buffer_size    = 16M
    sort_buffer_size        = 8M
    join_buffer_size        = 8M
    transaction-isolation=READ-COMMITTED
    binlog-format=mixed
    log-bin=mysql-bin
    max_binlog_size=300M
    log_bin_trust_function_creators = 1
    expire_logs_days=7
    server-id=1
