---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: namespace_PLACEHOLDER
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: "/var/lib/mysql"
              subPath: "mysql"
            - name: mysqld-config-vol
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQLD_ROOT_PASSWORD
          resources:
            requests:
              memory: "500M"
              cpu: "1"
            limits:
              memory: "1G"
              cpu: "2"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-disk
        - name: mysqld-config-vol
          configMap:
            name: mysqld-config
