apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- mysqld-pvc.yaml
- service.yaml

configMapGenerator:
- name: mysql-parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml

secretGenerator:
- name: mysql-secrets
  env: secrets.env

commonLabels:
  kustomize.component: mysql-server

