apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- namespace.yaml
- mysqld-pvc.yaml
- service.yaml

configMapGenerator:
- name: mysql-parameters
  envs:
  - params.env

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: mysql-secrets
  envs:
  - secrets.env

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: mysql-server
    app.kubernetes.io/name: mysql-server
    app.kubernetes.io/part-of: trino-on-k8s
    app.kubernetes.io/version: v25.04.01
    kustomize.component: mysql-server
