apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml

configMapGenerator:
- name: hive-metastore-parameters
  env: params.env
- name: hive-metastore-cfg
  files:
  - core-site.xml
  - metastore-site.xml

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: hive-metastore-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
configurations:
- params.yaml

secretGenerator:
- name: hive-metastore-secrets
  env: secrets.env

commonLabels:
  kustomize.component: hive-metastore

