apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- hive-init-schema.yaml  # commented for postgres image init
- deployment.yaml
- service.yaml

configMapGenerator:
- name: hive-metastore-parameters
  envs:
  - params.env
- name: hive-metastore-cm
  files:
  - core-site.xml
  - hive-site.xml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: hive-metastore-secrets
  envs:
  - secrets.env

labels:
- includeSelectors: true
  pairs:
    kustomize.component: hive-metastore