apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hive-init-schema.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: hive-metastore-parameters
  envs: 
  - params.env
- name: hive-metastore-cm
  files:
  - core-site.xml
  - hive-site.xml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: hive-metastore-secrets
  envs: 
  - secrets.env

commonLabels:
  kustomize.component: hive-metastore

