FROM openjdk:11-slim

ARG HADOOP_VERSION=3.3.2
ARG HIVE_VERSION=3.1.3

ARG hadoop_uri=https://archive.apache.org/dist/hadoop/core
ARG hive_uri=https://downloads.apache.org/hive
ARG mysql_uri=https://dev.mysql.com/get/Downloads/Connector-J

RUN apt-get update && apt-get install -y curl --no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

RUN curl ${hadoop_uri}/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz \
	| tar xvz -C /opt/  \
	&& ln -s /opt/hadoop-$HADOOP_VERSION /opt/hadoop \
	&& rm -r /opt/hadoop/share/doc 

RUN ln -s /opt/hadoop/share/hadoop/tools/lib/hadoop-aws* /opt/hadoop/share/hadoop/common/lib/ && \
    ln -s /opt/hadoop/share/hadoop/tools/lib/aws-java-sdk* /opt/hadoop/share/hadoop/common/lib/

ENV HADOOP_HOME="/opt/hadoop"
ENV PATH="/opt/hadoop/bin:${PATH}"

RUN curl ${hive_uri}/hive-$HIVE_VERSION/apache-hive-$HIVE_VERSION-bin.tar.gz \
	| tar xvz -C /opt/ \
	&& ln -s /opt/apache-hive-$HIVE_VERSION-bin /opt/hive

RUN curl -L ${mysql_uri}/mysql-connector-j-8.0.32.tar.gz \
	| tar xvz -C /opt/ \
	&& ln -s /opt/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar /opt/hadoop/share/hadoop/common/lib/ \
	&& ln -s /opt/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar /opt/hive/lib/ 

