apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
replicas:
- name: trino-worker
  count: 4

patchesStrategicMerge:
- nodeselectors.yaml

images:
- name: trinodb/trino
  newName: gcr.io/t3-dataintellence/trino
  newTag: "355"

namespace: trino
