ARG java_image_tag=17-jammy
FROM eclipse-temurin:${java_image_tag}
ARG app_version=1.5.0

LABEL org.opencontainers.image.source="https://github.com/prometheus/jmx-exporter" \
      org.opencontainers.image.title="jmx-exporter" \
      org.opencontainers.image.version="${app_version}"

COPY jmx_prometheus_standalone/target /opt/jmx-exporter
COPY examples /opt/jmx-exporter/examples
COPY entrypoint.sh /opt/

SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]

RUN set -ex && \
    apt-get update && \
    ln -s /lib /lib64 && \
    apt install -y bash coreutils curl procps zlib1g tini && \
    rm /bin/sh && \
    ln -sv /bin/bash /bin/sh && \
    useradd -u 1001 -m jmx && \
    chown jmx:jmx /opt/jmx-exporter && \
    chmod +x /opt/entrypoint.sh && \
    apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives


EXPOSE 5556
WORKDIR /opt/jmx-exporter
USER jmx

ENV APP_VERSION=${app_version}

ENTRYPOINT [ "/opt/entrypoint.sh" ]
CMD [ "5556", "examples/standalone_sample_config.yml" ]
