ARG java_image_tag=21
FROM azul/zulu-openjdk:${java_image_tag}

LABEL org.opencontainers.image.authors="Timothy C. Arland <tcarland at gmail dot com>" \
      org.opencontainers.image.base.name="azul/zulu-openjdk:21" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.description="Apache Hive Metastore Image" \
      org.opencontainers.image.source="https://github.com/tcarland/trino-on-k8s" \
      org.opencontainers.image.title="Hive Metastore" \
      org.opencontainers.image.version="fenrir"

ARG hadoop_version=3.4.1
ARG hive_version=3.1.3
ARG pg_jdbc_version=42.7.5
ARG aws_sdk_version=2.41.31

ARG hadoop_uri=https://archive.apache.org/dist/hadoop/core
ARG hive_uri=https://archive.apache.org/dist/hive
ARG pgsql_uri=https://jdbc.postgresql.org/download
ARG aws_sdk_uri=https://repo1.maven.org/maven2/software/amazon/awssdk/bundle

ENV HADOOP_HOME="/opt/hadoop"
ENV HIVE_HOME="/opt/hive"
ENV PATH="/opt/hadoop/bin:${PATH}"

RUN groupadd --gid 999 hive && \
    useradd -m --gid 999 --uid 999 hive && \
    apt-get update && \
    apt-get install --no-install-recommends -y curl && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L ${hadoop_uri}/hadoop-${hadoop_version}/hadoop-${hadoop_version}.tar.gz  | \
    tar xvz -C /opt/ && \
	ln -s /opt/hadoop-${hadoop_version} /opt/hadoop && \
	rm -r /opt/hadoop/share/doc && \
    ln -s /opt/hadoop/share/hadoop/tools/lib/hadoop-aws* /opt/hadoop/share/hadoop/common/lib/

RUN curl -L ${aws_sdk_uri}/${aws_sdk_version}/bundle-${aws_sdk_version}.jar \
    -o /opt/hadoop/share/hadoop/common/lib/bundle-${aws_sdk_version}.jar

RUN curl -L ${hive_uri}/hive-${hive_version}/apache-hive-${hive_version}-bin.tar.gz | \
	tar xvz -C /opt/ && \
	ln -s /opt/apache-hive-${hive_version}-bin /opt/hive

RUN curl -L ${pgsql_uri}/postgresql-${pg_jdbc_version}.jar -o /opt/hive/lib/postgresql-${pg_jdbc_version}.jar

COPY ca.cr[t] /opt/hive/ca.crt
RUN if [ -f /opt/hive/ca.crt ]; then \
        cp /opt/hive/ca.crt /usr/local/share/ca-certificates/tdh-ca.crt && \
        update-ca-certificates && \
        keytool -import -trustcacerts -cacerts -storepass changeit -noprompt -alias tdh-ca \
                -file /usr/local/share/ca-certificates/tdh-ca.crt; \
    fi 

WORKDIR /opt/hive
USER hive

ENTRYPOINT [ "/opt/hive/bin/hive", "--service", "metastore" ]
