apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- trino-virtualservice.yaml
- trino-gateway.yaml

configMapGenerator:
- name: trino-istio-params
  envs:
  - params.env

replacements:
- source:
    fieldPath: data.TRINO_DOMAINNAME
    kind: ConfigMap
    name: trino-istio-params
    version: v1
  targets:
  - select:
      name: trino-gateway
      kind: Gateway
    fieldPaths: 
    - spec.servers.*.hosts.0
  - select:
      name: trino-vs
      kind: VirtualService
    fieldPaths:
    - spec.hosts.0
  
generatorOptions:
  disableNameSuffixHash: true
