---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- pgsql-pvc.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: pgsql-params
  envs: 
  - params.env

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: pgsql-secret
  envs: 
  - secrets.env

labels:
- includeSelectors: true
  pairs:
    kustomize.component: postgres