apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: quay.io/tcarland/hive
  newName: gcr.io/myproject/hive
  newTag: v3.1.2-metis-2202.06

namespace: trino
