apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- ../../base

images:
- name: quay.io/tcarland/hive
  newName: gcr.io/myproject/hive
  newTag: v3.1.3-mimas-2504.15

secretGenerator:
- name: hive-truststore
  files:
  - truststore.jks=truststore.jks
generatorOptions:
  disableNameSuffixHash: true
  
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hive-metastore
      namespace: $(namespace)
    spec:
      selector:
        matchLabels:
          app: hive-metastore
      template:
        metadata:
          labels:
            app: hive-metastore
        spec:
          containers:
          - name: hive-metastore
            volumeMounts:
            - name: hive-truststore-vol
              mountPath: /opt/java/openjdk/lib/security/cacerts
              subPath: truststore.jks
              readOnly: true
            resources:
              requests:
                memory: "16G"
                cpu: "2"
              limits:
                memory: "24G"
                cpu: "4"
          volumes:
          - name: hive-truststore-vol
            secret:
              secretName: hive-truststore
