apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- ../../base

images:
- name: quay.io/tcarland/hive
  newName: gcr.io/myproject/hive
  newTag: v3.1.3-fenrir-2402.28
