apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trino

resources:
- ../../base

images:
- name: quay.io/tcarland/hive
  newName: gcr.io/myproject/hive
  newTag: v3.1.3-aegir-2503.03

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hive-metastore
      namespace: $(namespace)
    spec:
      selector:
        matchLabels:
          app: hive-metastore
      template:
        metadata:
          labels:
            app: hive-metastore
        spec:
          containers:
          - name: hive-metastore
            resources:
              requests:
                memory: "16G"
                cpu: "2"
              limits:
                memory: "24G"
                cpu: "4"
- target:
    kind: Service
    name: hive-metastore
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 9084
- target:
    kind: Deployment
    name: hive-metastore
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 9084
