name: Container Build and Test

on:
  push:
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Build Container
      run: docker build -t ${{ env.IMAGE_NAME }} -f Containerfile .

    - name: Run kustomize build of manifests
      run: docker run --rm ${{ env.IMAGE_NAME }} /bin/bash -c "cd /opt/tdh-k8s && S3_ENDPOINT=s3a://minio-svc S3_ACCESS_KEY=test S3_SECRET_KEY=test ./bin/trino-k8s-setup.sh && kustomize build mysql-server/ && kustomize build hive-metastore && kustomize build trino/"