name: 'Kustomize Build Action'

on:
  push:
    tags: [ 'v*' ]
    branches: [ 'develop' ]
  pull_request:
    branches: [ 'master', 'main' ]

env:
  TRINO_ENV: test
  S3_ENDPOINT: s3a://minio-svc
  S3_ACCESS_KEY: test
  S3_SECRET_KEY: test
  HIVE_DBPASSWORD: test
  TRINO_PASSWORD: TEST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Trino
        run: ./bin/trino-k8s-setup.sh

      - name: Set Trino account
        run: ./bin/trino-k8s-setup.sh -P trino

      - name: Build postgres
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './postgresdb'

      - name: Build hive-metastore
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './hive-metastore'

      - name: Build trino
        uses: tcarland/kustomize-build-action@v1
        with:
          kustomize_dir: './trino'
